# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Build Flutter IPA"
  lane :build do
    sh("flutter clean")
    sh("flutter pub get")
    sh("flutter build ipa --release")
  end

  desc "Upload to TestFlight"
  lane :beta do
  build
  upload_to_testflight(
    ipa: "../build/ios/ipa/travel.ipa",
    skip_waiting_for_build_processing: true
  )
end
  desc "App Store Release"
  lane :release do
    build
    upload_to_app_store(
      submit_for_review: true,
      automatic_release: false
    )
  end

end